language: go

sudo: false

go:
  - 1.11.x
  - 1.12.x

git:
  depth: 1

cache:
  directories:
    - vendor
    - $GOPATH/src


script:
  - git checkout $TRAVIS_COMMIT .  # travis.ci will overwrite to master branch
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  # - go test -bench ./...

after_script:
  - bash <(curl -s https://codecov.io/bash)
